apiVersion: 1

datasources:
  - name: IoTDB
    type: apache-iotdb-datasource
    access: proxy
    url: http://iotdb:18080
    isDefault: true
    jsonData:
      username: root
    secureJsonData:
      password: root
